spring:
  application:
    name: bookshop-modulith
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:bookshop
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: true

    show-sql: true
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: "*"
